package Views;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

import Models.SparePart;
import Controllers.SparePartController;
import java.sql.Types;
import javax.swing.table.DefaultTableModel;
import Utilities.jPanelGradient;

public class SupplierNpartsUI extends javax.swing.JFrame {

    public SupplierNpartsUI() {
        initComponents();
        Connect();
        
        bluePanel.setOpaque(false);
        orangePanel.setOpaque(false);
    }

    //create objects
    SparePartController spController = new SparePartController();
    SparePart sp;

    //data base connection
    Connection con;
    //insert/fetch data
    PreparedStatement pst;

    public void Connect() {
        String url = "jdbc:mysql://localhost:3306/timeticker";
        String user = "root";
        String password = "sysadmin@1122";


        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(InvoiceUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            con = DriverManager.getConnection(url, user, password);
        } catch (SQLException ex) {
            Logger.getLogger(InvoiceUI.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new jPanelGradient();
        bluePanel = new jPanelGradient();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        suppEmailTxt = new javax.swing.JTextField();
        suppIdTxt = new javax.swing.JTextField();
        suppNameTxt = new javax.swing.JTextField();
        updateSuppBtn = new javax.swing.JButton();
        addSuppBtn = new javax.swing.JButton();
        viewSuppBtn = new javax.swing.JButton();
        removeSuppBtn = new javax.swing.JButton();
        clearSuppBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        reqItemsTxt = new javax.swing.JTextField();
        sendEmailBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        suppliersTable = new javax.swing.JTable();
        viewAllSuppliers = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        orangePanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        partIdTxt = new javax.swing.JTextField();
        qtyTxt = new javax.swing.JTextField();
        priceTxt = new javax.swing.JTextField();
        partNameTxt = new javax.swing.JTextField();
        viewPartBtn = new javax.swing.JButton();
        addPartBtn = new javax.swing.JButton();
        updatePartBtn = new javax.swing.JButton();
        removePartBtn = new javax.swing.JButton();
        partClearBtn = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        partsTable = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        viewAllpartsBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bluePanel.setBackground(new java.awt.Color(102, 204, 255));
        bluePanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Supplier ID");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Enter Supplier Details ");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Supplier Email ");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Supplier Name ");

        suppEmailTxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        suppEmailTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suppEmailTxtActionPerformed(evt);
            }
        });

        suppIdTxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        suppIdTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suppIdTxtActionPerformed(evt);
            }
        });

        suppNameTxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        suppNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suppNameTxtActionPerformed(evt);
            }
        });

        updateSuppBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        updateSuppBtn.setText("update details");
        updateSuppBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateSuppBtnActionPerformed(evt);
            }
        });

        addSuppBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        addSuppBtn.setText("add supplier");
        addSuppBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSuppBtnActionPerformed(evt);
            }
        });

        viewSuppBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        viewSuppBtn.setText("view details");
        viewSuppBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewSuppBtnActionPerformed(evt);
            }
        });

        removeSuppBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        removeSuppBtn.setText("remove supplier");
        removeSuppBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeSuppBtnActionPerformed(evt);
            }
        });

        clearSuppBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        clearSuppBtn.setText("clear");
        clearSuppBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearSuppBtnActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Notify Suppliers");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Enter part names");

        reqItemsTxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        reqItemsTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reqItemsTxtActionPerformed(evt);
            }
        });

        sendEmailBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        sendEmailBtn.setText("send email");
        sendEmailBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendEmailBtnActionPerformed(evt);
            }
        });

        suppliersTable.setFont(new java.awt.Font("Segoe UI Historic", 0, 12)); // NOI18N
        suppliersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Supplier ID", "Supplier Name", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(suppliersTable);
        if (suppliersTable.getColumnModel().getColumnCount() > 0) {
            suppliersTable.getColumnModel().getColumn(0).setResizable(false);
            suppliersTable.getColumnModel().getColumn(1).setResizable(false);
            suppliersTable.getColumnModel().getColumn(2).setResizable(false);
        }

        viewAllSuppliers.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        viewAllSuppliers.setText("View Suppliers");
        viewAllSuppliers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAllSuppliersActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Suppliers List");

        javax.swing.GroupLayout bluePanelLayout = new javax.swing.GroupLayout(bluePanel);
        bluePanel.setLayout(bluePanelLayout);
        bluePanelLayout.setHorizontalGroup(
            bluePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bluePanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(290, 290, 290))
            .addGroup(bluePanelLayout.createSequentialGroup()
                .addGroup(bluePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bluePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(viewAllSuppliers)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(bluePanelLayout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(bluePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(bluePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel2)
                                .addComponent(jLabel4))
                            .addGroup(bluePanelLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(4, 4, 4)))
                        .addGap(25, 25, 25)
                        .addGroup(bluePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(bluePanelLayout.createSequentialGroup()
                                .addGroup(bluePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(suppNameTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                                    .addComponent(suppIdTxt)
                                    .addComponent(suppEmailTxt)
                                    .addComponent(reqItemsTxt))
                                .addGap(34, 34, 34)
                                .addGroup(bluePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(viewSuppBtn)
                                    .addComponent(updateSuppBtn)
                                    .addComponent(removeSuppBtn)
                                    .addComponent(sendEmailBtn)
                                    .addComponent(clearSuppBtn)
                                    .addComponent(addSuppBtn)))))
                    .addGroup(bluePanelLayout.createSequentialGroup()
                        .addGap(317, 317, 317)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        bluePanelLayout.setVerticalGroup(
            bluePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bluePanelLayout.createSequentialGroup()
                .addGroup(bluePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bluePanelLayout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(viewAllSuppliers)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 185, Short.MAX_VALUE))
                    .addGroup(bluePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel12)
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(46, 46, 46)
                        .addComponent(jLabel3)
                        .addGap(12, 12, 12)))
                .addGroup(bluePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bluePanelLayout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addGroup(bluePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(updateSuppBtn)
                            .addComponent(suppEmailTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(29, 29, 29)
                        .addComponent(removeSuppBtn)
                        .addGap(8, 8, 8)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(bluePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sendEmailBtn)
                            .addComponent(reqItemsTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)))
                    .addGroup(bluePanelLayout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addGroup(bluePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(viewSuppBtn)
                            .addComponent(suppNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(bluePanelLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(bluePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addSuppBtn)
                            .addComponent(jLabel2)
                            .addComponent(suppIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(34, 34, 34)
                .addComponent(clearSuppBtn)
                .addGap(46, 46, 46))
        );

        orangePanel.setBackground(new java.awt.Color(255, 153, 0));
        orangePanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Price");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Part Name");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Part ID");

        partIdTxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        partIdTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                partIdTxtActionPerformed(evt);
            }
        });

        qtyTxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        qtyTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtyTxtActionPerformed(evt);
            }
        });

        priceTxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        priceTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceTxtActionPerformed(evt);
            }
        });

        partNameTxt.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        partNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                partNameTxtActionPerformed(evt);
            }
        });

        viewPartBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        viewPartBtn.setText("view details");
        viewPartBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPartBtnActionPerformed(evt);
            }
        });

        addPartBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        addPartBtn.setText("add spare part");
        addPartBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPartBtnActionPerformed(evt);
            }
        });

        updatePartBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        updatePartBtn.setText("update details");
        updatePartBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatePartBtnActionPerformed(evt);
            }
        });

        removePartBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        removePartBtn.setText("remove part");
        removePartBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removePartBtnActionPerformed(evt);
            }
        });

        partClearBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        partClearBtn.setText("clear");
        partClearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                partClearBtnActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("Quantity");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setText("Enter Spare Part Details ");

        partsTable.setFont(new java.awt.Font("Segoe UI Historic", 0, 12)); // NOI18N
        partsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Part ID", "Part Name", "Quantity", "Supplier ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(partsTable);
        if (partsTable.getColumnModel().getColumnCount() > 0) {
            partsTable.getColumnModel().getColumn(0).setResizable(false);
            partsTable.getColumnModel().getColumn(1).setResizable(false);
            partsTable.getColumnModel().getColumn(2).setResizable(false);
        }

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton2.setText("Home");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        viewAllpartsBtn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        viewAllpartsBtn.setText("View Parts");
        viewAllpartsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAllpartsBtnActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Parts List");

        javax.swing.GroupLayout orangePanelLayout = new javax.swing.GroupLayout(orangePanel);
        orangePanel.setLayout(orangePanelLayout);
        orangePanelLayout.setHorizontalGroup(
            orangePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, orangePanelLayout.createSequentialGroup()
                .addContainerGap(87, Short.MAX_VALUE)
                .addGroup(orangePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, orangePanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(orangePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(viewAllpartsBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, orangePanelLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(302, 302, 302))))
            .addGroup(orangePanelLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(orangePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(orangePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(partIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(qtyTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(partNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(orangePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(viewPartBtn)
                    .addComponent(addPartBtn)
                    .addComponent(updatePartBtn)
                    .addComponent(removePartBtn)
                    .addComponent(partClearBtn))
                .addGap(57, 57, 57))
        );
        orangePanelLayout.setVerticalGroup(
            orangePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(orangePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addGap(26, 26, 26)
                .addGroup(orangePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(orangePanelLayout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(33, 33, 33)
                        .addComponent(viewAllpartsBtn)
                        .addGap(34, 34, 34)
                        .addComponent(jButton1))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addComponent(jLabel11)
                .addGap(28, 28, 28)
                .addGroup(orangePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(partNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addPartBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(orangePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(partIdTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewPartBtn))
                .addGap(42, 42, 42)
                .addGroup(orangePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(updatePartBtn)
                    .addComponent(priceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(34, 34, 34)
                .addGroup(orangePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(qtyTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removePartBtn))
                .addGap(36, 36, 36)
                .addComponent(partClearBtn)
                .addGap(121, 121, 121))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bluePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(orangePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bluePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(orangePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void partIdTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_partIdTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_partIdTxtActionPerformed

    private void suppEmailTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suppEmailTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_suppEmailTxtActionPerformed

    private void qtyTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtyTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_qtyTxtActionPerformed

    private void priceTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceTxtActionPerformed

    private void partNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_partNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_partNameTxtActionPerformed

    private void suppIdTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suppIdTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_suppIdTxtActionPerformed

    private void suppNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suppNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_suppNameTxtActionPerformed

    private void updateSuppBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateSuppBtnActionPerformed
        int suppId = Integer.parseInt(suppIdTxt.getText());
        String suppName = suppNameTxt.getText();
        String email = suppEmailTxt.getText();
        try {

            pst = con.prepareStatement("update Suppliers set supplierName=?,email=? where supplierId=?");
            pst.setString(1, suppName);
            pst.setString(2, email);
            pst.setInt(3, suppId);
            int result = pst.executeUpdate();

            if (result == 1) {
                JOptionPane.showMessageDialog(rootPane, "succesfully updated", "Sucess", 1);
            }

        } catch (SQLException ex) {
            Logger.getLogger(SupplierNpartsUI.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(rootPane, "can't update values", "error", 0);
        }


    }//GEN-LAST:event_updateSuppBtnActionPerformed

    private void removeSuppBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeSuppBtnActionPerformed
        int suppId = Integer.parseInt(suppIdTxt.getText());
        try {
            //set supplier ID to null
            pst = con.prepareStatement("update SpareParts set supplierId=?  where supplierId=?");
            pst.setNull(1, Types.NULL);
            pst.setInt(2, suppId);
            pst.executeUpdate();

            pst = con.prepareStatement("delete from Suppliers where supplierId=?");
            pst.setInt(1, suppId);

            int result = pst.executeUpdate();
            if (result == 1) {
                JOptionPane.showMessageDialog(rootPane, "Deleted Supplier =" + suppId, "Sucess", 1);
            }

        } catch (SQLException ex) {
            Logger.getLogger(SupplierNpartsUI.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(rootPane, "can't delete Supplier ID =" + suppId, "error", 0);
        }
    }//GEN-LAST:event_removeSuppBtnActionPerformed

    private void sendEmailBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendEmailBtnActionPerformed

        try {
            int suppId = Integer.parseInt(suppIdTxt.getText());
            String items = reqItemsTxt.getText();
            pst = con.prepareStatement("select supplierName,email from Suppliers where supplierId=?");
            pst.setInt(1, suppId);

            ResultSet rs = pst.executeQuery();//store values to result set
            rs.next();

            sp = spController.addSparePart();
            sp.sendEmail(rs.getString(2), items, rs.getString(1));
        } catch (SQLException ex) {
            Logger.getLogger(SupplierNpartsUI.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(rootPane, "Supplier ID field is empty", "error", 0);
        }


    }//GEN-LAST:event_sendEmailBtnActionPerformed

    private void updatePartBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatePartBtnActionPerformed
        String partName = partNameTxt.getText();
        int partId = Integer.parseInt(partIdTxt.getText());
        int qty = Integer.parseInt(qtyTxt.getText());
        double price = Double.parseDouble(priceTxt.getText());

        try {

            pst = con.prepareStatement("update SpareParts set partName=?,price=?,qty=? where partId=?");
            pst.setString(1, partName);
            pst.setDouble(2, price);
            pst.setInt(3, qty);
            pst.setInt(4, partId);

            int result = pst.executeUpdate();

            if (result == 1) {
                JOptionPane.showMessageDialog(rootPane, "succesfully updated", "Sucess", 1);
            }
        } catch (SQLException ex) {
            Logger.getLogger(SupplierNpartsUI.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(rootPane, "can't update values", "error", 0);
        }


    }//GEN-LAST:event_updatePartBtnActionPerformed

    private void removePartBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removePartBtnActionPerformed

        int partId = Integer.parseInt(partIdTxt.getText());
        try {
            pst = con.prepareStatement("delete from SpareParts where partId=?");
            pst.setInt(1, partId);

            int result = pst.executeUpdate();
            if (result == 1) {
                JOptionPane.showMessageDialog(rootPane, "succesfully remove Sparepart ", "Sucess", 1);
            }

        } catch (SQLException ex) {
            Logger.getLogger(SupplierNpartsUI.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(rootPane, "can't remove sparepart", "error", 0);
        }


    }//GEN-LAST:event_removePartBtnActionPerformed

    private void addSuppBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSuppBtnActionPerformed
        int suppId = Integer.parseInt(suppIdTxt.getText());
        String suppName = suppNameTxt.getText();
        String email = suppEmailTxt.getText();
        try {

            pst = con.prepareStatement("insert into Suppliers (supplierId,supplierName,email) values (?,?,?)");
            pst.setInt(1, suppId);
            pst.setString(2, suppName);
            pst.setString(3, email);

            int result = pst.executeUpdate();//this will return 0/1 depend on the value error wil display
            if (result == 1) {
                JOptionPane.showMessageDialog(rootPane, "successfully added supplier details", "Sucess", 1);

                //clean the entered values
                suppNameTxt.setText("");
                suppEmailTxt.setText("");
            }

        } catch (SQLException ex) {
            Logger.getLogger(SupplierNpartsUI.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(rootPane, "duplicate primary key :" + suppId, "Error", 0);
        }


    }//GEN-LAST:event_addSuppBtnActionPerformed

    private void viewSuppBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewSuppBtnActionPerformed
        int suppId = Integer.parseInt(suppIdTxt.getText());
        try {
            pst = con.prepareStatement("select * from Suppliers where supplierId=?");
            pst.setInt(1, suppId);
            ResultSet rs = pst.executeQuery();//store values to result set
            rs.next();

            suppNameTxt.setText(rs.getString(2));//get colum 2
            suppEmailTxt.setText(rs.getString(3));//get colum 3
        } catch (SQLException ex) {
            Logger.getLogger(SupplierNpartsUI.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(rootPane, "supplier id :" + suppId + " is invalid", "error", 0);
        }

    }//GEN-LAST:event_viewSuppBtnActionPerformed

    private void clearSuppBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearSuppBtnActionPerformed

        //clear fields
        suppIdTxt.setText("");
        suppNameTxt.setText("");
        suppEmailTxt.setText("");
    }//GEN-LAST:event_clearSuppBtnActionPerformed

    private void addPartBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPartBtnActionPerformed
        String partName = partNameTxt.getText();
        int partId = Integer.parseInt(partIdTxt.getText());
        double price = Double.parseDouble(priceTxt.getText());
        int qty = Integer.parseInt(qtyTxt.getText());
        int suppId = 0;
        if (!(suppIdTxt.getText().isEmpty())) {
            suppId = Integer.parseInt(suppIdTxt.getText());
        }

        try {
            pst = con.prepareStatement("insert into SpareParts (partName,partId,price,qty,supplierId)values (?,?,?,?,?)");
            pst.setString(1, partName);
            pst.setInt(2, partId);
            pst.setDouble(3, price);
            pst.setInt(4, qty);

            if (suppId == 0) {
                pst.setNull(5, Types.NULL);
            } else {
                pst.setInt(5, suppId);
            }

            int result = pst.executeUpdate();

            if (result == 1) {
                JOptionPane.showMessageDialog(rootPane, "successfully added Spare part details", "Sucess", 1);
            }

            //calculate total cost of the item
            sp = new SparePart();
            double totalCost = sp.clacTotalCost(qty, price);
            pst = con.prepareStatement("update SpareParts set totalCost=? where partId=?");
            pst.setDouble(1, totalCost);
            pst.setInt(2, partId);
            pst.executeUpdate();

        } catch (SQLException ex) {
            Logger.getLogger(SupplierNpartsUI.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(rootPane, "part ID =" + partId + " is alredy exists", "error", 0);
        }
    }//GEN-LAST:event_addPartBtnActionPerformed

    private void viewPartBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPartBtnActionPerformed
        int partId = Integer.parseInt(partIdTxt.getText());

        try {

            pst = con.prepareStatement("select * from SpareParts where partId=?");
            pst.setInt(1, partId);

            ResultSet rs = pst.executeQuery();//store values to result set
            rs.next();

            partNameTxt.setText(rs.getString(1));//get colum 1
            priceTxt.setText(rs.getString(3));//get colum 3
            qtyTxt.setText(rs.getString(4));//get colum 4

        } catch (SQLException ex) {
            Logger.getLogger(SupplierNpartsUI.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(rootPane, "supplier ID/part name Field is empty:", "error", 0);
        }

    }//GEN-LAST:event_viewPartBtnActionPerformed

    private void partClearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_partClearBtnActionPerformed
        partNameTxt.setText("");
        partIdTxt.setText("");
        qtyTxt.setText("");
        priceTxt.setText("");
        reqItemsTxt.setText("");

    }//GEN-LAST:event_partClearBtnActionPerformed

    private void reqItemsTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reqItemsTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reqItemsTxtActionPerformed

    private void viewAllpartsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAllpartsBtnActionPerformed
        try {
            pst = con.prepareStatement("select * from Spareparts");
            ResultSet rs = pst.executeQuery();
            //clean table
            DefaultTableModel model = (DefaultTableModel) partsTable.getModel();
            model.setRowCount(0);

            while (rs.next()) {
                String partID = String.valueOf(rs.getInt("partId"));
                String partName = rs.getString("partName");
                String quantiy = String.valueOf(rs.getInt("qty"));
                 String suppId= String.valueOf(rs.getInt("supplierId"));
                
                //create String array for store data into jtable
                String tbData[] = {partID, partName, quantiy,suppId};               
                DefaultTableModel tblModel = (DefaultTableModel) partsTable.getModel();

                //add string array data into jtable
                tblModel.addRow(tbData);

            }
        } catch (SQLException ex) {
            Logger.getLogger(SupplierNpartsUI.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_viewAllpartsBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //clean table
        DefaultTableModel model = (DefaultTableModel) suppliersTable.getModel();
        model.setRowCount(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        MainUI ui = new MainUI();
        ui.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void viewAllSuppliersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAllSuppliersActionPerformed

        try {
            pst = con.prepareStatement("select * from Suppliers ");
            ResultSet rs = pst.executeQuery();
            //clean table
            DefaultTableModel model = (DefaultTableModel) suppliersTable.getModel();
            model.setRowCount(0);
            
            while (rs.next()) {
                String email = rs.getString("email");
                String suppID = String.valueOf(rs.getInt("supplierId"));
                String suppName = rs.getString("supplierName");
                
                //create String array for store data into jtable
                String tbData[] = {suppID, suppName, email};
                DefaultTableModel tblModel = (DefaultTableModel) suppliersTable.getModel();
                
                //add string array data into jtable
                tblModel.addRow(tbData);
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(SupplierNpartsUI.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_viewAllSuppliersActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SupplierNpartsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SupplierNpartsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SupplierNpartsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SupplierNpartsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SupplierNpartsUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPartBtn;
    private javax.swing.JButton addSuppBtn;
    private javax.swing.JPanel bluePanel;
    private javax.swing.JButton clearSuppBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel orangePanel;
    private javax.swing.JButton partClearBtn;
    private javax.swing.JTextField partIdTxt;
    private javax.swing.JTextField partNameTxt;
    private javax.swing.JTable partsTable;
    private javax.swing.JTextField priceTxt;
    private javax.swing.JTextField qtyTxt;
    private javax.swing.JButton removePartBtn;
    private javax.swing.JButton removeSuppBtn;
    private javax.swing.JTextField reqItemsTxt;
    private javax.swing.JButton sendEmailBtn;
    private javax.swing.JTextField suppEmailTxt;
    private javax.swing.JTextField suppIdTxt;
    private javax.swing.JTextField suppNameTxt;
    private javax.swing.JTable suppliersTable;
    private javax.swing.JButton updatePartBtn;
    private javax.swing.JButton updateSuppBtn;
    private javax.swing.JButton viewAllSuppliers;
    private javax.swing.JButton viewAllpartsBtn;
    private javax.swing.JButton viewPartBtn;
    private javax.swing.JButton viewSuppBtn;
    // End of variables declaration//GEN-END:variables
}
